export enum Permission {
  TenantCreate = 'tenant:create',
  TenantRead = 'tenant:read',
  TenantUpdate = 'tenant:update',
  TenantDelete = 'tenant:delete',
  UserCreate = 'user:create',
  UserRead = 'user:read',
  UserUpdate = 'user:update',
  UserDelete = 'user:delete',
  RoleCreate = 'role:create',
  RoleRead = 'role:read',
  RoleUpdate = 'role:update',
  RoleAssign = 'role:assign',
  RoleDelete = 'role:delete',
  CustomerCreate = 'customer:create',
  CustomerRead = 'customer:read',
  CustomerUpdate = 'customer:update',
  CustomerDelete = 'customer:delete',
  DealCreate = 'deal:create',
  DealRead = 'deal:read',
  DealUpdate = 'deal:update',
  DealDelete = 'deal:delete',
  ActivityCreate = 'activity:create',
  ActivityRead = 'activity:read',
  ActivityUpdate = 'activity:update',
  ActivityDelete = 'activity:delete',
}
